# Generated by Django 5.0.3 on 2024-03-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('no_of_houses', models.PositiveIntegerField()),
                ('available_houses', models.PositiveIntegerField()),
            ],
        ),
    ]
