# Generated by Django 5.0.3 on 2024-03-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0002_rename_no_of_houses_building_total_number_of_houses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='building_name',
            field=models.CharField(default='HomeHive', max_length=255),
        ),
        migrations.AddField(
            model_name='building',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='Housing.amenity'),
        ),
    ]
