# Generated by Django 5.0.3 on 2024-03-22 04:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0003_amenity_building_building_name_building_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid phone number format (XXX-XXX-XXXX)', regex='\\d{3}-\\d{3}-\\d{4}')])),
                ('number_of_rooms', models.PositiveIntegerField(default=1)),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='Housing.building')),
            ],
        ),
    ]
