# Generated by Django 5.0.3 on 2024-03-24 23:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0005_caretaker_alter_tenant_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='caretaker', to='Housing.building'),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='phone_number',
            field=models.CharField(default='0700000000', max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid phone number format (XXX-XXX-XXXX)', regex='\\d{10}')]),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='name',
            field=models.CharField(default='Nill', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='Housing.building'),
        ),
    ]
