# Generated by Django 5.0.3 on 2024-03-24 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0006_caretaker_building_caretaker_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='Housing.building'),
        ),
    ]
