# Generated by Django 5.0.3 on 2024-03-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0007_alter_tenant_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='house_number',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
