# Generated by Django 5.0.3 on 2024-04-01 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housing', '0009_totaltenants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='total_number_of_houses',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
